// Barrel export — named exports only, no default exports
export { safeJsonParse } from './safe-json-parse.js'
export type { ParseFailure } from './safe-json-parse.js'
export { validateTelemetryPayload, INTENT_TYPES } from './schemas.js'
export type { ValidationFailure, ValidatedTelemetryPayload, ValidatedIntent, IntentTypeValue } from './schemas.js'
export { createIngestionPipeline, createAsyncIngestionPipeline } from './pipeline.js'
export type { PersistFn, AsyncPersistFn, PersistFailure, IngestionError, PipelineResult } from './pipeline.js'
export { createIngestionHandler, createAsyncIngestionHandler } from './black-hole.js'
export type { IngestionResponse, AuditEntry, AuditFn } from './black-hole.js'
export { transformIntentToEvent, transformIntentsToEvents } from './transform.js'
export type { InsertableEvent as TransformableEvent } from './transform.js'
