import { writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'

const COMMANDS = {
  init: 'Scaffold a new Valence project',
  dev: 'Start the development server',
  migrate: 'Run pending database migrations',
  build: 'Build the project for production'
} as const

type Command = keyof typeof COMMANDS

const commandMap: Record<Command, (args: ReadonlyArray<string>) => Promise<void>> = {
  init: runInit,
  dev: runDev,
  migrate: runMigrate,
  build: runBuild
}

export async function run (argv: ReadonlyArray<string>): Promise<void> {
  const command = argv[0] as Command | undefined

  if (command === undefined || !(command in commandMap)) {
    printUsage()
    return
  }

  await commandMap[command](argv.slice(1))
}

function printUsage (): void {
  console.log('Usage: valence <command>\n')
  console.log('Commands:')
  for (const [name, desc] of Object.entries(COMMANDS)) {
    console.log(`  ${name.padEnd(12)} ${desc}`)
  }
}

async function runInit (args: ReadonlyArray<string>): Promise<void> {
  const projectName = args[0] ?? 'my-valence-app'
  const dbName = projectName.replace(/[^a-z0-9_]/g, '_')
  const dir = join(process.cwd(), projectName)

  console.log(`\n  Creating ${projectName}...\n`)

  await mkdir(dir, { recursive: true })
  await mkdir(join(dir, 'collections'), { recursive: true })
  await mkdir(join(dir, 'migrations'), { recursive: true })
  await mkdir(join(dir, 'public'), { recursive: true })
  await mkdir(join(dir, 'templates'), { recursive: true })

  // package.json
  await writeFile(join(dir, 'package.json'), JSON.stringify({
    name: projectName,
    version: '0.1.0',
    type: 'module',
    scripts: {
      dev: 'valence dev',
      build: 'valence build',
      migrate: 'valence migrate',
      start: 'node dist/server.js'
    },
    dependencies: {
      '@valencets/valence': '^0.1.0',
      '@valencets/cms': '^0.1.0',
      '@valencets/db': '^0.1.0'
    },
    devDependencies: {
      typescript: '^5.9.3'
    }
  }, null, 2) + '\n')

  // valence.config.ts
  await writeFile(join(dir, 'valence.config.ts'), `import { defineConfig, collection, field } from '@valencets/valence'

export default defineConfig({
  db: {
    host: process.env.DB_HOST ?? 'localhost',
    port: Number(process.env.DB_PORT ?? 5432),
    database: process.env.DB_NAME ?? '${dbName}',
    username: process.env.DB_USER ?? 'postgres',
    password: process.env.DB_PASSWORD ?? ''
  },
  server: {
    port: Number(process.env.PORT ?? 3000)
  },
  collections: [
    collection({
      slug: 'posts',
      labels: { singular: 'Post', plural: 'Posts' },
      fields: [
        field.text({ name: 'title', required: true }),
        field.slug({ name: 'slug', required: true, unique: true, slugFrom: 'title' }),
        field.textarea({ name: 'body' }),
        field.boolean({ name: 'published' }),
        field.date({ name: 'publishedAt' })
      ]
    }),

    collection({
      slug: 'users',
      auth: true,
      fields: [
        field.text({ name: 'name', required: true })
      ]
    })
  ],
  admin: {
    pathPrefix: '/admin',
    requireAuth: true
  }
})
`)

  // tsconfig.json
  await writeFile(join(dir, 'tsconfig.json'), JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      strict: true,
      noImplicitAny: true,
      noImplicitReturns: true,
      strictNullChecks: true,
      noUncheckedIndexedAccess: true,
      exactOptionalPropertyTypes: true,
      outDir: 'dist',
      rootDir: '.',
      declaration: true,
      sourceMap: true
    },
    include: ['*.ts', 'collections/**/*.ts']
  }, null, 2) + '\n')

  // .env.example
  await writeFile(join(dir, '.env.example'), `# Database
DB_HOST=localhost
DB_PORT=5432
DB_NAME=${dbName}
DB_USER=postgres
DB_PASSWORD=

# Server
PORT=3000

# Security (generate a random string for production)
CMS_SECRET=change-me-before-deploying
`)

  // .gitignore
  await writeFile(join(dir, '.gitignore'), `node_modules/
dist/
.env
uploads/
*.log
`)

  // README
  await writeFile(join(dir, 'README.md'), `# ${projectName}

Built with [Valence](https://github.com/valencets/valence).

## Setup

\`\`\`bash
pnpm install
cp .env.example .env    # Edit with your database credentials
createdb ${dbName}      # Create the PostgreSQL database
valence migrate         # Run database migrations
valence dev             # Start development server
\`\`\`

Site: http://localhost:3000
Admin: http://localhost:3000/admin
`)

  // First migration
  await writeFile(join(dir, 'migrations', '001-init.sql'), `-- Generated by valence init
-- Creates the posts and users tables

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS "posts" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "title" TEXT NOT NULL,
  "slug" TEXT NOT NULL UNIQUE,
  "body" TEXT,
  "published" BOOLEAN DEFAULT false,
  "publishedAt" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "email" TEXT NOT NULL UNIQUE,
  "password_hash" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ
);
`)

  console.log('  Done. Your project is ready.\n')
  console.log('  Next steps:\n')
  console.log(`    cd ${projectName}`)
  console.log('    pnpm install')
  console.log('    cp .env.example .env')
  console.log(`    createdb ${dbName}`)
  console.log('    valence migrate')
  console.log('    valence dev\n')
  console.log('  Site:  http://localhost:3000')
  console.log('  Admin: http://localhost:3000/admin\n')
}

async function runDev (): Promise<void> {
  console.log('Starting Valence dev server...')
  console.log('TODO: load valence.config.ts, wire CMS + telemetry, start HTTP server')
}

async function runMigrate (): Promise<void> {
  console.log('Running migrations...')
  console.log('TODO: load valence.config.ts, connect to DB, run pending migrations')
}

async function runBuild (): Promise<void> {
  console.log('Building for production...')
  console.log('TODO: generate migrations from schema diff, compile templates')
}
