import { ok, err } from 'neverthrow'
import type { Result } from 'neverthrow'
import type { CollectionConfig, FieldConfig } from '@valencets/cms'

export const CollectionValidationCode = {
  INVALID_COLLECTION_SLUG: 'INVALID_COLLECTION_SLUG',
  DUPLICATE_COLLECTION_SLUG: 'DUPLICATE_COLLECTION_SLUG',
  INVALID_SLUG_FROM: 'INVALID_SLUG_FROM',
  RESERVED_FIELD_NAME: 'RESERVED_FIELD_NAME',
  DUPLICATE_FIELD_NAME: 'DUPLICATE_FIELD_NAME',
  INVALID_RELATION_TO: 'INVALID_RELATION_TO'
} as const

export type CollectionValidationCode = typeof CollectionValidationCode[keyof typeof CollectionValidationCode]

export interface CollectionValidationError {
  readonly code: CollectionValidationCode
  readonly message: string
}

const SLUG_PATTERN = /^[a-z][a-z0-9-]*$/

const RESERVED_FIELD_NAMES = new Set([
  'id',
  'created_at',
  'updated_at',
  'deleted_at',
  '_status',
  'publish_at'
])

function validateSlugFormat (slug: string): Result<void, CollectionValidationError> {
  if (!SLUG_PATTERN.test(slug)) {
    return err({
      code: CollectionValidationCode.INVALID_COLLECTION_SLUG,
      message: `Collection slug "${slug}" is invalid. Slugs must start with a lowercase letter and contain only lowercase letters, numbers, and hyphens.`
    })
  }
  return ok(undefined)
}

function validateSlugFromFields (
  collection: CollectionConfig
): Result<void, CollectionValidationError> {
  const fieldNames = new Set(collection.fields.map((f) => f.name))
  const slugFields = collection.fields.filter(
    (f): f is Extract<FieldConfig, { type: 'slug' }> => f.type === 'slug'
  )

  for (const slugField of slugFields) {
    const { slugFrom } = slugField
    if (slugFrom !== undefined && !fieldNames.has(slugFrom)) {
      return err({
        code: CollectionValidationCode.INVALID_SLUG_FROM,
        message: `Collection "${collection.slug}" has a slug field "${slugField.name}" with slugFrom: "${slugFrom}", but no field named "${slugFrom}" exists in that collection.`
      })
    }
  }

  return ok(undefined)
}

function validateFieldNames (
  collection: CollectionConfig
): Result<void, CollectionValidationError> {
  const seen = new Set<string>()

  for (const field of collection.fields) {
    if (RESERVED_FIELD_NAMES.has(field.name)) {
      return err({
        code: CollectionValidationCode.RESERVED_FIELD_NAME,
        message: `Collection "${collection.slug}" has a field named "${field.name}", which is a reserved column name auto-generated by Valence.`
      })
    }

    if (seen.has(field.name)) {
      return err({
        code: CollectionValidationCode.DUPLICATE_FIELD_NAME,
        message: `Collection "${collection.slug}" has duplicate field name "${field.name}". Each field name must be unique within a collection.`
      })
    }
    seen.add(field.name)
  }

  return ok(undefined)
}

function validateRelationFields (
  collection: CollectionConfig,
  allSlugs: ReadonlySet<string>
): Result<void, CollectionValidationError> {
  const relationFields = collection.fields.filter(
    (f): f is Extract<FieldConfig, { type: 'relation' }> => f.type === 'relation'
  )

  for (const field of relationFields) {
    if (!allSlugs.has(field.relationTo)) {
      return err({
        code: CollectionValidationCode.INVALID_RELATION_TO,
        message: `Collection "${collection.slug}" has a relation field "${field.name}" with relationTo: "${field.relationTo}", but no collection with that slug exists.`
      })
    }
  }

  return ok(undefined)
}

export function validateCollections (
  collections: readonly CollectionConfig[]
): Result<void, CollectionValidationError> {
  const seen = new Set<string>()
  const allSlugs = new Set(collections.map((c) => c.slug))

  for (const col of collections) {
    const formatResult = validateSlugFormat(col.slug)
    if (formatResult.isErr()) {
      return formatResult
    }

    if (seen.has(col.slug)) {
      return err({
        code: CollectionValidationCode.DUPLICATE_COLLECTION_SLUG,
        message: `Duplicate collection slug "${col.slug}". Each collection must have a unique slug.`
      })
    }
    seen.add(col.slug)

    const fieldNamesResult = validateFieldNames(col)
    if (fieldNamesResult.isErr()) {
      return fieldNamesResult
    }

    const slugFromResult = validateSlugFromFields(col)
    if (slugFromResult.isErr()) {
      return slugFromResult
    }

    const relationResult = validateRelationFields(col, allSlugs)
    if (relationResult.isErr()) {
      return relationResult
    }
  }

  return ok(undefined)
}
