import { ok, err } from '@valencets/resultkit'
import type { Result } from '@valencets/resultkit'
import type { CollectionConfig, FieldConfig } from '@valencets/cms'

export const CollectionValidationCode = {
  INVALID_COLLECTION_SLUG: 'INVALID_COLLECTION_SLUG',
  DUPLICATE_COLLECTION_SLUG: 'DUPLICATE_COLLECTION_SLUG',
  INVALID_SLUG_FROM: 'INVALID_SLUG_FROM',
  RESERVED_FIELD_NAME: 'RESERVED_FIELD_NAME',
  DUPLICATE_FIELD_NAME: 'DUPLICATE_FIELD_NAME',
  INVALID_RELATION_TO: 'INVALID_RELATION_TO'
} as const

export type CollectionValidationCode = typeof CollectionValidationCode[keyof typeof CollectionValidationCode]

export interface CollectionValidationError {
  readonly code: CollectionValidationCode
  readonly message: string
}

const SLUG_PATTERN = /^[a-z][a-z0-9-]*$/

const RESERVED_FIELD_NAMES = new Set([
  'id',
  'created_at',
  'updated_at',
  'deleted_at',
  '_status',
  'publish_at'
])

function collectSlugFormatErrors (slug: string): CollectionValidationError[] {
  if (!SLUG_PATTERN.test(slug)) {
    const suggestion = slug.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/^[^a-z]+/, '')
    const hint = suggestion.length > 0 ? ` (e.g. "${suggestion}")` : ''
    return [{
      code: CollectionValidationCode.INVALID_COLLECTION_SLUG,
      message: `Collection slug "${slug}" is invalid. Slugs must start with a lowercase letter and contain only lowercase letters, numbers, and hyphens${hint}.`
    }]
  }
  return []
}

function collectSlugFromErrors (
  collection: CollectionConfig
): CollectionValidationError[] {
  const fieldNames = new Set(collection.fields.map((f) => f.name))
  const slugFields = collection.fields.filter(
    (f): f is Extract<FieldConfig, { type: 'slug' }> => f.type === 'slug'
  )

  const errors: CollectionValidationError[] = []
  for (const slugField of slugFields) {
    const { slugFrom } = slugField
    if (slugFrom !== undefined && !fieldNames.has(slugFrom)) {
      errors.push({
        code: CollectionValidationCode.INVALID_SLUG_FROM,
        message: `Collection "${collection.slug}" field "${slugField.name}" has slugFrom: "${slugFrom}", but no field named "${slugFrom}" exists in that collection. Add a field named "${slugFrom}" or update slugFrom to reference an existing field.`
      })
    }
  }

  return errors
}

function collectFieldNameErrors (
  collection: CollectionConfig
): CollectionValidationError[] {
  const seen = new Set<string>()
  const errors: CollectionValidationError[] = []

  for (const field of collection.fields) {
    if (RESERVED_FIELD_NAMES.has(field.name)) {
      errors.push({
        code: CollectionValidationCode.RESERVED_FIELD_NAME,
        message: `Collection "${collection.slug}" field "${field.name}" uses a reserved column name that is auto-generated by Valence. Rename this field to avoid conflicts with "${field.name}".`
      })
    } else if (seen.has(field.name)) {
      errors.push({
        code: CollectionValidationCode.DUPLICATE_FIELD_NAME,
        message: `Collection "${collection.slug}" has a duplicate field name "${field.name}". Each field name must be unique within a collection. Rename one of the "${field.name}" fields.`
      })
    }
    seen.add(field.name)
  }

  return errors
}

function collectRelationErrors (
  collection: CollectionConfig,
  allSlugs: ReadonlySet<string>
): CollectionValidationError[] {
  const relationFields = collection.fields.filter(
    (f): f is Extract<FieldConfig, { type: 'relation' }> => f.type === 'relation'
  )

  const errors: CollectionValidationError[] = []
  for (const field of relationFields) {
    if (!allSlugs.has(field.relationTo)) {
      errors.push({
        code: CollectionValidationCode.INVALID_RELATION_TO,
        message: `Collection "${collection.slug}" field "${field.name}" has relationTo: "${field.relationTo}", but no collection with that slug exists. Add a collection with slug "${field.relationTo}" or update the relationTo value.`
      })
    }
  }

  return errors
}

export function validateCollections (
  collections: readonly CollectionConfig[]
): Result<void, CollectionValidationError[]> {
  const allErrors: CollectionValidationError[] = []
  const seen = new Set<string>()
  const allSlugs = new Set(collections.map((c) => c.slug))

  for (const col of collections) {
    allErrors.push(...collectSlugFormatErrors(col.slug))

    if (seen.has(col.slug)) {
      allErrors.push({
        code: CollectionValidationCode.DUPLICATE_COLLECTION_SLUG,
        message: `Duplicate collection slug "${col.slug}". Each collection must have a unique slug. Rename one of the "${col.slug}" collections.`
      })
    }
    seen.add(col.slug)

    allErrors.push(...collectFieldNameErrors(col))
    allErrors.push(...collectSlugFromErrors(col))
    allErrors.push(...collectRelationErrors(col, allSlugs))
  }

  if (allErrors.length > 0) {
    return err(allErrors)
  }

  return ok(undefined)
}
